version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: bbq-tracker-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file: ./env/.env.dev
    environment:
      - NODE_ENV=dev
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: bbq-tracker-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo_data:
